const ENUM_STAT = Object.freeze([
    "speed",
    "special-defense",
    "special-attack",
    "defense",
    "attack",
    "hp"
]);

const ENUM_NATURE = Object.freeze([
    "Adamant",
    "Bashful",
    "Bold",
    "Brave",	
    "Calm",
    "Careful",
    "Docile",
    "Gentle",
    "Hardy",
    "Hasty",
    "Impish",
    "Jolly",
    "Lax",
    "Lonely",
    "Mild",
    "Modest",
    "Naive",
    "Naughty",
    "Quiet",
    "Quirky",
    "Rash",
    "Relaxed",
    "Sassy",
    "Serious",
    "Timid"
]);

const MODIFIER_NATURE = Object.freeze(
    {
        "Adamant":{
            "speed":1,
            "special-defense":1,
            "special-attack":0.9,
            "defense":1,
            "attack":1.1
        },
        "Bashful":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Bold":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":1.1,
            "attack":0.9
        },
        "Brave":{
            "speed":0.9,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":1.1
        },
        "Calm":{
            "speed":1,
            "special-defense":1.1,
            "special-attack":1,
            "defense":1,
            "attack":0.9
        },
        "Careful":{
            "speed":1,
            "special-defense":1.1,
            "special-attack":0.9,
            "defense":1,
            "attack":1
        },
        "Docile":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Gentle":{
            "speed":1,
            "special-defense":1.1,
            "special-attack":1,
            "defense":0.9,
            "attack":1
        },
        "Hardy":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Hasty":{
            "speed":1.1,
            "special-defense":1,
            "special-attack":1,
            "defense":0.9,
            "attack":1
        },
        "Impish":{
            "speed":1,
            "special-defense":1,
            "special-attack":0.9,
            "defense":1.1,
            "attack":1
        },
        "Jolly":{
            "speed":1.1,
            "special-defense":1,
            "special-attack":0.9,
            "defense":1,
            "attack":1
        },
        "Lax":{
            "speed":1,
            "special-defense":0.9,
            "special-attack":1,
            "defense":1.1,
            "attack":1
        },
        "Lonely":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":0.9,
            "attack":1.1
        },
        "Mild":{
            "speed":1,
            "special-defense":1,
            "special-attack":1.1,
            "defense":0.9,
            "attack":1
        },
        "Modest":{
            "speed":1,
            "special-defense":1,
            "special-attack":1.1,
            "defense":1,
            "attack":0.9
        },
        "Naive":{
            "speed":1.1,
            "special-defense":0.9,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Naughty":{
            "speed":1,
            "special-defense":0.9,
            "special-attack":1,
            "defense":1,
            "attack":1.1
        },
        "Quiet":{
            "speed":0.9,
            "special-defense":1,
            "special-attack":1.1,
            "defense":1,
            "attack":1
        },
        "Quirky":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Rash":{
            "speed":1,
            "special-defense":0.9,
            "special-attack":1.1,
            "defense":1,
            "attack":1
        },
        "Relaxed":{
            "speed":0.9,
            "special-defense":1,
            "special-attack":1,
            "defense":1.1,
            "attack":1
        },
        "Sassy":{
            "speed":0.9,
            "special-defense":1.1,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Serious":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Timid":{
            "speed":1.1,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":0.9
        }
    }
)

const ENUM_TYPE = Object.freeze([
    "normal",
    "fighting",
    "flying",
    "poison",
    "ground",
    "rock",
    "bug",
    "ghost",
    "steel",
    "fire",
    "water",
    "grass",
    "electric",
    "psychic",
    "ice",
    "dragon",
    "dark",
    "fairy",
    "unknown",
    "shadow"    
]);

const ENUM_MOVE_LEARN_METHOD = Object.freeze([
    "level-up",
    "tutor",
    "machine",
    "stadium-surfing-pikachu",
    "light-ball-egg",
    "colosseum-purification",
    "xd-shadow",
    "xd-purification",
    "form-change",
    "egg"
]);

const ENUM_GENDER = Object.freeze([
    "Male",
    "Female"
]);

module.exports= {
    ENUM_TYPE,
    ENUM_NATURE,
    ENUM_STAT,
    ENUM_MOVE_LEARN_METHOD,
    ENUM_GENDER,
    MODIFIER_NATURE
}