// TODO : do all items https://www.serebii.net/dungeon2/items.shtml

const ENUM_STATUS = Object.freeze({
    NORMAL:'NORMAL',
    BURN:'BURN',
    SLEEP:'SLEEP',
    POISON:'POISON'
})


const MDO = Object.freeze({
    GRIMY_FOOD:'GRIMY_FOOD',
    APPLE: 'APPLE',
    GOLDEN_APPLE: 'GOLDEN_APPLE',
    RED_GUMMI: 'RED_GUMMI',
    SILVER_GUMMI: 'SILVER_GUMMI'
});

const MDO_TILESET = Object.freeze({
    RED_GUMMI:'RED_GUMMI',
    ORANGE_GUMMI:'ORANGE_GUMMI',
    SILVER_GUMMI:'SILVER_GUMMI',
    GOLD_GUMMI:'GOLD_GUMMI',
    GRASS_GUMMI:'GRASS_GUMMI',
    GREEN_GUMMY:'GREEN_GUMMY',
    SKY_GUMMI:'SKY_GUMMI',
    BLUE_GUMMI:'BLUE_GUMMI',
    ROYAL_GUMMI:'ROYAL_GUMMI',
    PURPLE_GUMMI:'PURPLE_GUMMI',
    PINK_GUMMI:'PINK_GUMMI',
    BLACK_GUMMI:'BLACK_GUMMI',
    BROWN_GUMMI:'BROWN_GUMMI',
    WHITE_GUMMI:'WHITE_GUMMI',
    GREY_GUMMI:'GREY_GUMMI',
    MYSTERIOUS_GUMMI:'MYSTERIOUS_GUMMI',
    YELLOW_GUMMI:'YELLOW_GUMMI',
    BAND:'BAND',
    GLASSES:'GLASSES',
    MUSIC_KEY:'MUSIC_KEY',
    AMBER_TEAR:'AMBER_TEAR',
    MIRACLE_CHEST:'MIRACLE_CHEST',
    WONDER_CHEST:'WONDER_CHEST',
    BOTTLE:'BOTTLE',
    GABITE_SCALE:'GABITE_SCALE',
    SEED:'SEED',
    CACNEA_SPIKE:'CACNEA_SPIKE',
    CORSOLA_TWIG:'CORSOLA_TWIG',
    GOLD_FANG:'GOLD_FANG',
    IRON_THORN:'IRON_THORN',
    SILVER_SPIKE:'SILVER_SPIKE',
    STICK:'STICK',
    GOLDEN_TWIG:'GOLDEN_TWIG',
    ANCIENT_FOSSIL:'ANCIENT_FOSSIL',
    GEO_PEBBLE:'GEO_PEBBLE',
    GRAVELROCK:'GRAVELROCK',
    RED_APPLE:'RED_APPLE',
    GOLDEN_APPLE:'GOLDEN_APPLE',
    GRIMY_FOOD:'GRIMY_FOOD',
    CHERI_BERRY:'CHERI_BERRY',
    CHESTO_BERRY:'CHESTO_BERRY',
    ORAN_BERRY:'ORAN_BERRY',
    PECHA_BERRY:'PECHA_BERRY',
    RAWST_BERRY:'RAWST_BERRY',
    SITRUS_BERRY:'SITRUS_BERRY',
    ORB:'ORB',
    CS:'CS',
    CT:'CT',
    RED_CHEST:'RED_CHEST',
    BROWN_CHEST:'BROWN_CHEST',
    BLUE_CHEST:'BLUE_CHEST',
    BIG_RED_CHEST:'BIG_RED_CHEST',
    BIG_BLUE_CHEST:'BIG_BLUE_CHEST',
    ENIGMA_PART:'ENIGMA_PART',
    SECRET_STONEPLATE:'SECRET_STONEPLATE',
    UNOWN_STONE:'UNOWN_STONE',
    HIDDEN_GOLD:'HIDDEN_GOLD',
    POKEDOLLAR:'POKEDOLLAR',
    KEY:'KEY',
    LINK_BOX:'LINK_BOX',
    MYSTERIOUS_EGG:'MYSTERIOUS_EGG',
    PAPER:'PAPER',
    STATUE:'STATUE',
    MAGMARIZER:'MAGMARIZER',
    ELECTRIZER:'ELECTRIZER',
    RAZOR_FANG:'RAZOR_FANG',
    LINK_CABLE:'LINK_CABLE',
    RAZOR_CLAW:'RAZOR_CLAW',
    REAPER_CLOWTH:'REAPER_CLOWTH',
    DUBIOUS_DISC:'DUBIOUS_DISC',
    METAL_COAT:'METAL_COAT',
    PROTECTOR:'PROTECTOR',
    UPGRADE:'UPGRADE',
    DEEPSEATOOTH:'DEEPSEATOOTH',
    FIRE_STONE:'FIRE_STONE',
    SUN_STONE:'SUN_STONE',
    SHINY_STONE:'SHINY_STONE',
    THUNDERSTONE:'THUNDERSTONE',
    LEAF_STONE:'LEAF_STONE',
    OVAL_STONE:'OVAL_STONE',
    WATER_STONE:'WATER_STONE',
    DAWN_STONE:'DAWN_STONE',
    DUSK_STONE:'DUSK_STONE',
    MOON_STONE:'MOON_STONE',
    BROWN_STONE:'BROWN_STONE',
    MT_CORONET_STONE:'MT_CORONET_STONE',
    MOSS_ROCK:'MOSS_ROCK',
    FROZEN_ROCK:'FROZEN_ROCK',
    SUN_RIBBON:'SUN_RIBBON',
    BEAUTY_SCARF:'BEAUTY_SCARF',
    LUNAR_RIBBON:'LUNAR_RIBBON',
    DRAGON_SCALE:'DRAGON_SCALE',
    DEEP_SEA_SCALE:'DEEP_SEA_SCALE'
});

const ENUM_STAT = Object.freeze([
    "speed",
    "special-defense",
    "special-attack",
    "defense",
    "attack",
    "hp"
]);

const ENUM_NATURE = Object.freeze([
    "Adamant",
    "Bashful",
    "Bold",
    "Brave",	
    "Calm",
    "Careful",
    "Docile",
    "Gentle",
    "Hardy",
    "Hasty",
    "Impish",
    "Jolly",
    "Lax",
    "Lonely",
    "Mild",
    "Modest",
    "Naive",
    "Naughty",
    "Quiet",
    "Quirky",
    "Rash",
    "Relaxed",
    "Sassy",
    "Serious",
    "Timid"
]);

const MODIFIER_NATURE = Object.freeze(
    {
        "Adamant":{
            "speed":1,
            "special-defense":1,
            "special-attack":0.9,
            "defense":1,
            "attack":1.1
        },
        "Bashful":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Bold":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":1.1,
            "attack":0.9
        },
        "Brave":{
            "speed":0.9,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":1.1
        },
        "Calm":{
            "speed":1,
            "special-defense":1.1,
            "special-attack":1,
            "defense":1,
            "attack":0.9
        },
        "Careful":{
            "speed":1,
            "special-defense":1.1,
            "special-attack":0.9,
            "defense":1,
            "attack":1
        },
        "Docile":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Gentle":{
            "speed":1,
            "special-defense":1.1,
            "special-attack":1,
            "defense":0.9,
            "attack":1
        },
        "Hardy":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Hasty":{
            "speed":1.1,
            "special-defense":1,
            "special-attack":1,
            "defense":0.9,
            "attack":1
        },
        "Impish":{
            "speed":1,
            "special-defense":1,
            "special-attack":0.9,
            "defense":1.1,
            "attack":1
        },
        "Jolly":{
            "speed":1.1,
            "special-defense":1,
            "special-attack":0.9,
            "defense":1,
            "attack":1
        },
        "Lax":{
            "speed":1,
            "special-defense":0.9,
            "special-attack":1,
            "defense":1.1,
            "attack":1
        },
        "Lonely":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":0.9,
            "attack":1.1
        },
        "Mild":{
            "speed":1,
            "special-defense":1,
            "special-attack":1.1,
            "defense":0.9,
            "attack":1
        },
        "Modest":{
            "speed":1,
            "special-defense":1,
            "special-attack":1.1,
            "defense":1,
            "attack":0.9
        },
        "Naive":{
            "speed":1.1,
            "special-defense":0.9,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Naughty":{
            "speed":1,
            "special-defense":0.9,
            "special-attack":1,
            "defense":1,
            "attack":1.1
        },
        "Quiet":{
            "speed":0.9,
            "special-defense":1,
            "special-attack":1.1,
            "defense":1,
            "attack":1
        },
        "Quirky":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Rash":{
            "speed":1,
            "special-defense":0.9,
            "special-attack":1.1,
            "defense":1,
            "attack":1
        },
        "Relaxed":{
            "speed":0.9,
            "special-defense":1,
            "special-attack":1,
            "defense":1.1,
            "attack":1
        },
        "Sassy":{
            "speed":0.9,
            "special-defense":1.1,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Serious":{
            "speed":1,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":1
        },
        "Timid":{
            "speed":1.1,
            "special-defense":1,
            "special-attack":1,
            "defense":1,
            "attack":0.9
        }
    }
)

const ENUM_TYPE = Object.freeze([
    "normal",
    "fighting",
    "flying",
    "poison",
    "ground",
    "rock",
    "bug",
    "ghost",
    "steel",
    "fire",
    "water",
    "grass",
    "electric",
    "psychic",
    "ice",
    "dragon",
    "dark",
    "fairy",
    "unknown",
    "shadow"    
]);

const ENUM_MOVE_LEARN_METHOD = Object.freeze([
    "level-up",
    "tutor",
    "machine",
    "stadium-surfing-pikachu",
    "light-ball-egg",
    "colosseum-purification",
    "xd-shadow",
    "xd-purification",
    "form-change",
    "egg"
]);

const ENUM_GENDER = Object.freeze([
    "Male",
    "Female"
]);

module.exports= {
    ENUM_TYPE,
    ENUM_NATURE,
    ENUM_STAT,
    ENUM_MOVE_LEARN_METHOD,
    ENUM_GENDER,
    MODIFIER_NATURE,
    MDO,
    MDO_TILESET,
    ENUM_STATUS
}