// TODO : do all items https://www.serebii.net/dungeon2/items.shtml

const ENUM_STATUS = Object.freeze({
    NORMAL:'NORMAL',
    BURN:'BURN',
    SLEEP:'SLEEP',
    POISON:'POISON',
    PARALYSIS:'PARALYSIS'
})


const MDO = Object.freeze({
    GRIMY_FOOD:'GRIMY_FOOD',
    APPLE: 'APPLE',
    GOLDEN_APPLE: 'GOLDEN_APPLE',
    RED_GUMMI: 'RED_GUMMI',
    SILVER_GUMMI: 'SILVER_GUMMI',
    CHERI_BERRY:'CHERI_BERRY',
    CHESTO_BERRY:'CHESTO_BERRY',
    ORAN_BERRY:'ORAN_BERRY',
    PECHA_BERRY:'PECHA_BERRY',
    SITRUS_BERRY:'SITRUS_BERRY',
    RAWST_BERRY:'RAWST_BERRY',
    UPSTAIRS:'UPSTAIRS',
    DOWNSTAIRS:'DOWNSTAIRS',
    SPAWN_POINT_PLAYER:'SPAWN_POINT_PLAYER',
    SPAWN_POINT_IA:'SPAWN_POINT_IA'
});

const MDO_LOOK = Object.freeze({
    RED_GUMMI:'RED_GUMMI',
    ORANGE_GUMMI:'ORANGE_GUMMI',
    SILVER_GUMMI:'SILVER_GUMMI',
    GOLD_GUMMI:'GOLD_GUMMI',
    GRASS_GUMMI:'GRASS_GUMMI',
    GREEN_GUMMY:'GREEN_GUMMY',
    SKY_GUMMI:'SKY_GUMMI',
    BLUE_GUMMI:'BLUE_GUMMI',
    ROYAL_GUMMI:'ROYAL_GUMMI',
    PURPLE_GUMMI:'PURPLE_GUMMI',
    PINK_GUMMI:'PINK_GUMMI',
    BLACK_GUMMI:'BLACK_GUMMI',
    BROWN_GUMMI:'BROWN_GUMMI',
    WHITE_GUMMI:'WHITE_GUMMI',
    GREY_GUMMI:'GREY_GUMMI',
    MYSTERIOUS_GUMMI:'MYSTERIOUS_GUMMI',
    YELLOW_GUMMI:'YELLOW_GUMMI',
    BAND:'BAND',
    GLASSES:'GLASSES',
    MUSIC_KEY:'MUSIC_KEY',
    AMBER_TEAR:'AMBER_TEAR',
    MIRACLE_CHEST:'MIRACLE_CHEST',
    WONDER_CHEST:'WONDER_CHEST',
    BOTTLE:'BOTTLE',
    GABITE_SCALE:'GABITE_SCALE',
    SEED:'SEED',
    CACNEA_SPIKE:'CACNEA_SPIKE',
    CORSOLA_TWIG:'CORSOLA_TWIG',
    GOLD_FANG:'GOLD_FANG',
    IRON_THORN:'IRON_THORN',
    SILVER_SPIKE:'SILVER_SPIKE',
    STICK:'STICK',
    GOLDEN_TWIG:'GOLDEN_TWIG',
    ANCIENT_FOSSIL:'ANCIENT_FOSSIL',
    GEO_PEBBLE:'GEO_PEBBLE',
    GRAVELROCK:'GRAVELROCK',
    RED_APPLE:'RED_APPLE',
    GOLDEN_APPLE:'GOLDEN_APPLE',
    GRIMY_FOOD:'GRIMY_FOOD',
    CHERI_BERRY:'CHERI_BERRY',
    CHESTO_BERRY:'CHESTO_BERRY',
    ORAN_BERRY:'ORAN_BERRY',
    PECHA_BERRY:'PECHA_BERRY',
    RAWST_BERRY:'RAWST_BERRY',
    SITRUS_BERRY:'SITRUS_BERRY',
    ORB:'ORB',
    CS:'CS',
    CT:'CT',
    RED_CHEST:'RED_CHEST',
    BROWN_CHEST:'BROWN_CHEST',
    BLUE_CHEST:'BLUE_CHEST',
    BIG_RED_CHEST:'BIG_RED_CHEST',
    BIG_BLUE_CHEST:'BIG_BLUE_CHEST',
    ENIGMA_PART:'ENIGMA_PART',
    SECRET_STONEPLATE:'SECRET_STONEPLATE',
    UNOWN_STONE:'UNOWN_STONE',
    HIDDEN_GOLD:'HIDDEN_GOLD',
    POKEDOLLAR:'POKEDOLLAR',
    KEY:'KEY',
    LINK_BOX:'LINK_BOX',
    MYSTERIOUS_EGG:'MYSTERIOUS_EGG',
    PAPER:'PAPER',
    STATUE:'STATUE',
    MAGMARIZER:'MAGMARIZER',
    ELECTRIZER:'ELECTRIZER',
    RAZOR_FANG:'RAZOR_FANG',
    LINK_CABLE:'LINK_CABLE',
    RAZOR_CLAW:'RAZOR_CLAW',
    REAPER_CLOWTH:'REAPER_CLOWTH',
    DUBIOUS_DISC:'DUBIOUS_DISC',
    METAL_COAT:'METAL_COAT',
    PROTECTOR:'PROTECTOR',
    UPGRADE:'UPGRADE',
    DEEPSEATOOTH:'DEEPSEATOOTH',
    FIRE_STONE:'FIRE_STONE',
    SUN_STONE:'SUN_STONE',
    SHINY_STONE:'SHINY_STONE',
    THUNDERSTONE:'THUNDERSTONE',
    LEAF_STONE:'LEAF_STONE',
    OVAL_STONE:'OVAL_STONE',
    WATER_STONE:'WATER_STONE',
    DAWN_STONE:'DAWN_STONE',
    DUSK_STONE:'DUSK_STONE',
    MOON_STONE:'MOON_STONE',
    BROWN_STONE:'BROWN_STONE',
    MT_CORONET_STONE:'MT_CORONET_STONE',
    MOSS_ROCK:'MOSS_ROCK',
    FROZEN_ROCK:'FROZEN_ROCK',
    SUN_RIBBON:'SUN_RIBBON',
    BEAUTY_SCARF:'BEAUTY_SCARF',
    LUNAR_RIBBON:'LUNAR_RIBBON',
    DRAGON_SCALE:'DRAGON_SCALE',
    DEEP_SEA_SCALE:'DEEP_SEA_SCALE',
    UPSTAIRS:'UPSTAIRS',
    DOWNSTAIRS:'DOWNSTAIRS'
});

const ENUM_STAT = Object.freeze({
    SPEED:'SPEED',
    SPECIAL_DEFENSE:'SPECIAL_DEFENSE',
    SPECIAL_ATTACK:'SPECIAL_ATTACK',
    DEFENSE:'DEFENSE',
    ATTACK:'ATTACK',
    HP:'HP'
});


const ENUM_NATURE = Object.freeze([
    "ADAMANT",
    "BASHFUL",
    "BOLD",
    "BRAVE",	
    "CALM",
    "CAREFUL",
    "DOCILE",
    "GENTLE",
    "HARDY",
    "HASTY",
    "IMPISH",
    "JOLLY",
    "LAX",
    "LONELY",
    "MILD",
    "MODEST",
    "NAIVE",
    "NAUGHTY",
    "QUIET",
    "QUIRKY",
    "RASH",
    "RELAXED",
    "SASSY",
    "SERIOUS",
    "TIMID"
]);

const MODIFIER_NATURE = Object.freeze(
    {
        "ADAMANT":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":0.9,
            "DEFENSE":1,
            "ATTACK":1.1
        },
        "BASHFUL":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1,
            "ATTACK":1
        },
        "BOLD":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1.1,
            "ATTACK":0.9
        },
        "BRAVE":{
            "SPEED":0.9,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1,
            "ATTACK":1.1
        },
        "CALM":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1.1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1,
            "ATTACK":0.9
        },
        "CAREFUL":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1.1,
            "SPECIAL_ATTACK":0.9,
            "DEFENSE":1,
            "ATTACK":1
        },
        "DOCILE":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1,
            "ATTACK":1
        },
        "GENTLE":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1.1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":0.9,
            "ATTACK":1
        },
        "HARDY":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1,
            "ATTACK":1
        },
        "HASTY":{
            "SPEED":1.1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":0.9,
            "ATTACK":1
        },
        "IMPISH":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":0.9,
            "DEFENSE":1.1,
            "ATTACK":1
        },
        "JOLLY":{
            "SPEED":1.1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":0.9,
            "DEFENSE":1,
            "ATTACK":1
        },
        "LAX":{
            "SPEED":1,
            "SPECIAL_DEFENSE":0.9,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1.1,
            "ATTACK":1
        },
        "LONELY":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":0.9,
            "ATTACK":1.1
        },
        "MILD":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1.1,
            "DEFENSE":0.9,
            "ATTACK":1
        },
        "MODEST":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1.1,
            "DEFENSE":1,
            "ATTACK":0.9
        },
        "NAIVE":{
            "SPEED":1.1,
            "SPECIAL_DEFENSE":0.9,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1,
            "ATTACK":1
        },
        "NAUGHTY":{
            "SPEED":1,
            "SPECIAL_DEFENSE":0.9,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1,
            "ATTACK":1.1
        },
        "QUIET":{
            "SPEED":0.9,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1.1,
            "DEFENSE":1,
            "ATTACK":1
        },
        "QUIRKY":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1,
            "ATTACK":1
        },
        "RASH":{
            "SPEED":1,
            "SPECIAL_DEFENSE":0.9,
            "SPECIAL_ATTACK":1.1,
            "DEFENSE":1,
            "ATTACK":1
        },
        "RELAXED":{
            "SPEED":0.9,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1.1,
            "ATTACK":1
        },
        "SASSY":{
            "SPEED":0.9,
            "SPECIAL_DEFENSE":1.1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1,
            "ATTACK":1
        },
        "SERIOUS":{
            "SPEED":1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1,
            "ATTACK":1
        },
        "TIMID":{
            "SPEED":1.1,
            "SPECIAL_DEFENSE":1,
            "SPECIAL_ATTACK":1,
            "DEFENSE":1,
            "ATTACK":0.9
        }
    }
)

const ENUM_TYPE = Object.freeze([
    "normal",
    "fighting",
    "flying",
    "poison",
    "ground",
    "rock",
    "bug",
    "ghost",
    "steel",
    "fire",
    "water",
    "grass",
    "electric",
    "psychic",
    "ice",
    "dragon",
    "dark",
    "fairy",
    "unknown",
    "shadow"    
]);

const ENUM_MOVE_LEARN_METHOD = Object.freeze([
    "level-up",
    "tutor",
    "machine",
    "stadium-surfing-pikachu",
    "light-ball-egg",
    "colosseum-purification",
    "xd-shadow",
    "xd-purification",
    "form-change",
    "egg"
]);

const ENUM_GENDER = Object.freeze([
    "Male",
    "Female"
]);

const ENUM_RARITY = Object.freeze({
	COMMON:1,
	UNCOMMON:0.2,
	RARE:0.04,
	EPIC:0.008,
	LEGENDARY:0.00016
});

module.exports= {
    ENUM_TYPE,
    ENUM_NATURE,
    ENUM_STAT,
    ENUM_MOVE_LEARN_METHOD,
    ENUM_GENDER,
    MODIFIER_NATURE,
    MDO,
    MDO_LOOK,
    ENUM_STATUS,
	ENUM_RARITY
}